### ISSUE TITLE
create development-split with www3.threefold.io update

### ISSUE THREAD

**Issue by Mik-TF** [threefoldfoundation/www_threefold_io#331]
# Feature

Soon I will push changes to add the website link checker to check threefold.io's links (see [here](https://github.com/threefoldfoundation/www_threefold_io/issues/293))

For this to be effective, it would be nice to have the same as we did for info_grid, where we host on www3 development-split, which is pushed online.

So we would have for this repo:

- www.threefold.io at master branch
- www2.threefold.io at development branch (protected)
- www3.threefold.io at development-split branch
  - we can use this branch to test changes before making a PR to development (so we trigger the website link checker workflow)

For more info on the dev-split on info_grid, see [here](https://github.com/threefoldtech/info_grid/blob/development-split/.github/workflows/manual_update_development_split.yml)

## In brief

- Add www3.threefold.io workflow linked to development-split branch.

@PeterNashaat Do you think it's feasible? 

The file would look like this (not saying it would be 100% this):

```
name: www3.threefold_io
on: 
  push:
    branches: [ development-split ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: pushing latest change on www3.threefold.io
      uses: appleboy/ssh-action@master
      with:
        host: www3.threefold.io
        username: webuser
        key: ${{ secrets.TF_SECRET }}
        port: 34022
        script: |
          cd websites/www3/www_threefold_io/
          git log -1
          git fetch
          git reset --hard origin/development
          sed -i "s/https:\/\/www.threefold.io/https:\/\/www3.threefold.io/g" config.toml
          ./build.sh
```
