### ISSUE TITLE
TFT metadata

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/www_threefold_io#63]
The following content needs to be at https://threefold.io/.well-known/stellar.toml with cors headers (`Access-Control-Allow-Origin: *` enabled.

Please replace the image url's with the following image placed on a reachable location:
[icon.png.zip](https://github.com/threefoldfoundation/www_threefold_io/files/6266971/icon.png.zip)

```toml
[[CURRENCIES]]
code = "TFT"
issuer = "GBOVQKJYHXRR3DX6NOX2RRYFRCUMSADGDESTDNBDS6CDVLGVESRTAC47"
display_decimals = 2
name = "Threefold Token"
desc = "A digital currency used to buy autonomous and decentralized Internet services (compute, storage, and application) on the ThreeFold Network"
image = "https://www.threefold.io/assets/3fold_icon.png"

[[CURRENCIES]]
code = "TFTA"
issuer = "GBUT4GP5GJ6B3XW5PXENHQA7TXJI5GOPW3NF4W3ZIW6OOO4ISY6WNLN2"
display_decimals = 2
name = "Threefold Token"
desc = "A digital currency used to buy autonomous and decentralized Internet services (compute, storage, and application) on the ThreeFold Network"
image = "https://www.threefold.io/assets/3fold_icon.png"
```
